k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: arn:aws:eks:eu-west-2:464700364571:cluster/eks-staging
  currentCluster: arn:aws:eks:eu-west-2:464700364571:cluster/eks-staging
  clusters:
    arn:aws:eks:ap-southeast-1:251316246111:cluster/staging:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - infra
        - default
      view:
        active: context
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-west-2:464700364571:cluster/eks-staging:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    k3d-louis-k3d:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/5f/nxhkc6jx6316_m6rmjsdr05r0000gn/T/k9s-screens-louishuyng
