add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold blue)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
# error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Sets user-defined palette
# palette = "catppuccin_mocha"

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[](green) 󰄾"
error_symbol = "[](red)"
vicmd_symbol = "[ ](green)"

[directory]
truncation_length = 4
# Catppuccin 'lavender'
style = "bold lavender"

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = "  "

[golang]
format = '[ $version](bold cyan) '

[kubernetes]
symbol = '☸'
disabled = false
detect_files = ['k8s', 'Dockerfile']
detect_extensions = ['yaml']
format = '[$symbol$context( \($namespace\))]($style) '
