format = """
$directory\
$git_branch\
$sudo\
$cmd_duration\
$jobs\
$line_break\
$character
"""

[line_break]
disabled = true

[directory]
style = "blue"
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " "
truncate_to_repo = false

[character]
success_symbol = "[](fg:#91C0BE)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[git_branch]
style="yellow"
format = "[󰅁$branch*󰅂]($style) "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"
