apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: identity

spec:
  weighted:
    services:
      - name: webserver-simple-service
        namespace: development
        weight: 1
        port: 80
