[colors]
draw_bold_text_with_bright_colors = false

[colors.normal]
black = "#363944"
blue = "#79b8ff"
cyan = "#76e3ea"
green = "#85e89d"
magenta = "#b392f0"
red = "#f97583"
white = "#f4f4f4"
yellow = "#d29922"

[colors.primary]
background = "#0F0F0F"
foreground = "#e1e4e8"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_title = false
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"
dynamic_padding = false
